name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy code to DigitalOcean
        if: contains(github.event.head_commit.message, 'prod')
        run: |
          ssh -i ~/.ssh/id_ed25519 frappe@${{ secrets.PROD_IP }} "
          cd /home/frappe/frappe-bench/apps/raplbaddi && \
          PULL_OUTPUT=\$(git pull origin production) && \
          echo \"\$PULL_OUTPUT\" && \
          if [[ \$PULL_OUTPUT != *'Already up to date.'* ]]; then
              echo 'Changes detected.';
          else
              echo 'Already up-to-date.';
          fi

          # Migrate if 'migrate' keyword is in the commit message
          if [[ \$(echo '${{ github.event.head_commit.message }}' | grep -i 'migrate') ]]; then
              echo 'Running bench migrate...';
              cd /home/frappe/frappe-bench && bench migrate;
          fi

          # Build if 'build' keyword is in the commit message
          if [[ \$(echo '${{ github.event.head_commit.message }}' | grep -i 'build') ]]; then
              echo 'Running bench build...';
              cd /home/frappe/frappe-bench && bench build;
          fi

          # Restart if 'restart' keyword is in the commit message
          if [[ \$(echo '${{ github.event.head_commit.message }}' | grep -i 'restart') ]]; then
              echo 'Running bench restart...';
              cd /home/frappe/frappe-bench && bench restart;
          fi
          "

      - name: Skip deployment
        if: ${{ !contains(github.event.head_commit.message, 'p2p') }}
        run: echo "Commit message does not contain 'p2p'. Skipping deployment."